# Generated by Django 4.1 on 2022-08-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reportestr',
            field=models.CharField(default='', max_length=20000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
