# Generated by Django 4.1 on 2022-08-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_report_reportestr_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysrbds',
            name='tmpfile',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
