# Generated by Django 4.1 on 2022-08-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_querysrbds_tmpfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysrbds',
            name='otp_is_valid',
            field=models.BooleanField(null=True),
        ),
    ]
