# Generated by Django 4.1 on 2022-08-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_querysrbds_otp_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querysrbds',
            name='tmpfile',
        ),
    ]
