# Generated by Django 4.1 on 2022-08-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_remove_querysrbds_tmpfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysrbds',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
