# Generated by Django 4.1 on 2022-08-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_querysrbds_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querysrbds',
            name='filename',
            field=models.CharField(max_length=40),
        ),
    ]
