# Generated by Django 4.1 on 2022-08-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_alter_querysrbds_id_alter_resultreport_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='queryid',
            field=models.IntegerField(null=True),
        ),
    ]
