# Generated by Django 4.1 on 2022-10-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_report_queryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysrbds',
            name='t_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
