version: "3.8"

services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - .ddata:/var/lib/postgresql/data
    app:
        container_name: EdeCodeRestApiComplement
        restart: always
        build: .
        ports:
            - "80:8080"
        volumes:
            - .:/app
        depends_on:
            - db
    #redis:
    #    image: redis:alpine
    #celery:
    #    restart: always
    #    build:
    #        context: .
    #    command: celery -A "reporteede" worker -l debug -B
    #    volumes:
    #        - .:/app
    #    environment:
    #        - DB_HOST=app
    #        - DB_NAME=postgres
    #        - DB_USER=postgres
    #        - DB_PASS=supersecretpassword
    #    depends_on:
    #        - db
    #        - redis
    #        - app
