version: "2.0"

services: 
    web:
        container_name: EdeCodeRestApiComplement
        restart: always
        build: .
        ports: 
            - "80:8080" 
        links: 
            - mysql
        volumes: 
            - .:/app
    mysql:
        container_name: mysql
        image: mysql:8
        ports: 
            - "3306:3306"
        volumes: 
            - ../mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=S3cret
            #- MYSQL_PASSWORD=An0thrS3crt
            #- MYSQL_USER=citizix_user
            - MYSQL_DATABASE=edecode_api