version: "3.8"

services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - .dbdata:/var/lib/postgresql/data
    web:
        container_name: EdeCodeRestApiComplement
        restart: always
        build: .
        ports:
            - "80:8080"
        volumes:
            - .:/app
        depends_on:
            - db
