version: "3"

services: 
    web:
        container_name: EdeCodeRestApiComplement
        restart: always
        build: .
        ports: 
            - "80:8080" 
        links: 
            - mongo
        volumes: 
            - .:/app
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"
        logging:
            driver: none
        volumes: 
            - D:/mongo:/data/db